# Generated by Django 5.2.1 on 2025-06-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите ваш е-майл', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Введите ФИО', max_length=255)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'получатель',
                'verbose_name_plural': 'получатели',
                'ordering': ['email', 'full_name'],
            },
        ),
    ]
