# Generated by Django 5.2.1 on 2025-06-05 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_mailing_sendattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email', 'full_name'], 'permissions': [('can_view_recipient', 'Can view recipient')], 'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
        migrations.AddField(
            model_name='recipient',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
