# Generated by Django 5.2.1 on 2025-06-05 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_recipient_options_recipient_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Can view mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'], 'permissions': [('can_view_message', 'Can view message')], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.AlterModelOptions(
            name='sendattempt',
            options={'ordering': ['-date_time'], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_date_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_date_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время первой отправки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='date_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата и время попытки'),
        ),
        migrations.AddField(
            model_name='sendattempt',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sendattempt', to='messenger.recipient', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='messenger.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(related_name='mailings', to='messenger.recipient', verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='sendattempt',
            name='mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sendattempt', to='messenger.mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='sendattempt',
            name='server_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='sendattempt',
            name='status',
            field=models.CharField(choices=[('Done', 'Успешно'), ('Failed', 'Не успешно')], db_index=True, default='Failed', max_length=20, verbose_name='Статус'),
        ),
    ]
